name: causal-ai-experiments
channels:
  - conda-forge
  - defaults
dependencies:
  # Python and core packages
  - python=3.11
  - pip
  
  # Jupyter and notebook environment
  - jupyter
  - jupyterlab
  - notebook
  - ipykernel
  - ipywidgets
  
  # Data science fundamentals
  - numpy
  - pandas
  - scipy
  - scikit-learn
  
  # Visualization
  - matplotlib
  - seaborn
  - plotly
  - graphviz
  - python-graphviz
  

    
  # Additional useful packages for causal analysis
  - networkx
  - statsmodels

    # Causal AI core packages
  - pip:
    - pgmpy>=0.1.21
    - dowhy>=0.10.1
  
 